# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0"

Vagrant.configure("2") do |config|

    config.vm.guest = :windows

    config.windows.halt_timeout = 15

    config.vm.communicator = "winrm"

    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.ssh.insert_key = false

    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        config.vm.box = "asymmetric-effort/virtualbox/windows/10"
        config.vm.define "windows_10"
        v.gui = true
        v.customize ["modifyvm", :id, "--memory", 4096]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
end
