#
# Windows section.  All the windows boxes should go in this section, ordered alphabetically because this
#                   list is going to get very long.
#

.PHONY: windows/7
windows/7:
	$(MAKE) PACKER_FILE="packer/windows/7.json" build

.PHONY: windows/10
windows/10:
	$(MAKE) PACKER_FILE="packer/windows/10.json" build

.PHONY: windows/81
windows/81:
	$(MAKE) PACKER_FILE="packer/windows/81.json" build

.PHONY: windows/2008_r2
windows/2008_r2:
	$(MAKE) PACKER_FILE="packer/windows/2008_r2.json" build

.PHONY: windows/2008_r2_core
windows/2008_r2_core:
	$(MAKE) PACKER_FILE="packer/windows/2008_r2_core.json" build

.PHONY: windows/2012
windows/2012:
	$(MAKE) PACKER_FILE="packer/windows/2012.json" build

.PHONY: windows/2012_r2
windows/2012_r2:
	$(MAKE) PACKER_FILE="packer/windows/2012_r2.json" build

.PHONY: windows/2012_r2_core
windows/2012_r2_core:
	$(MAKE) PACKER_FILE="packer/windows/2012_r2_core.json" build

.PHONY: windows/2012_r2_hyperv
windows/2012_r2_hyperv:
	$(MAKE) PACKER_FILE="packer/windows/2012_r2_hyperv.json" build

.PHONY: windows/2016
windows/2016:
	$(MAKE) PACKER_FILE="packer/windows/2016.json" build

