#
# Linux section.  All Linux stuff should go here ordered alphabetically.  The list that could go here is long.
#                 names should be linux/<family>/<version>.  For example: linux/ubuntu/18.04_server
#
# ToDo: Add ubuntu 18.04 server.