#
# Windows section.  All the windows boxes should go in this section, ordered alphabetically because this
#                   list is going to get very long.
#
.PHONY: windows/7
windows/7:
	packer build -force -color=true -var headless=false packer/windows/7.json

.PHONY: windows/10
windows/10:
	packer build -force -color=true -var headless=false packer/windows/10.json

.PHONY: windows/81
windows/81:
	packer build -force -color=true -var headless=false packer/windows/81.json

.PHONY: windows/2008_r2
windows/2008_r2:
	packer build -force -color=true -var headless=false packer/windows/2008_r2.json

.PHONY: windows/2008_r2_core
windows/2008_r2_core:
	packer build -force -color=true -var headless=false packer/windows/2008_r2_core.json

.PHONY: windows/2012
windows/2012:
	packer build -force -color=true -var headless=false packer/windows/2012.json

.PHONY: windows/2012_r2
windows/2012_r2:
	packer build -force -color=true -var headless=false packer/windows/2012_r2.json

.PHONY: windows/2012_r2_core
windows/2012_r2_core:
	packer build -force -color=true -var headless=false packer/windows/2012_r2_core.json

.PHONY: windows/2012_r2_hyperv
windows/2012_r2_hyperv:
	packer build -force -color=true -var headless=false packer/windows/2012_r2_hyperv.json

.PHONY: windows/2016
windows/2016:
	packer build -force -color=true -var headless=false packer/windows/2016.json